package foods

import "github.com/dhruvv301292/nutrichat/internal/nutrition"

var SeedFoods = []nutrition.Food{
	{
		Name:         "Chicken Thigh, Raw",
		Calories:     145,
		Protein:      21,
		Carbs:        0,
		Fat:          7,
		Fiber:        0,
		Sodium:       175,
		Unit:         "grams",
		UnitQuantity: 112,
	},
	{
		Name:         "Quest Protein Shake",
		Calories:     230,
		Protein:      45,
		Carbs:        4,
		Fat:          4,
		Fiber:        0,
		Sodium:       300,
		Unit:         "bottle",
		UnitQuantity: 1,
	},
	{
		Name:         "Egg, XL",
		Calories:     80,
		Protein:      7,
		Carbs:        0,
		Fat:          5,
		Fiber:        0,
		Sodium:       80,
		Unit:         "egg",
		UnitQuantity: 1,
	},
	{
		Name:         "Ground beef, 90-10, raw",
		Calories:     200,
		Protein:      23,
		Carbs:        0,
		Fat:          11,
		Fiber:        0,
		Sodium:       75,
		Unit:         "grams",
		UnitQuantity: 113,
	},
	{
		Name:         "David Protein bar",
		Calories:     150,
		Protein:      28,
		Carbs:        12,
		Fat:          2,
		Fiber:        1,
		Sodium:       170,
		Unit:         "bar",
		UnitQuantity: 1,
	},
}
